### ISSUE TITLE
可否考虑加入米游社里官方信息的收集？

### ISSUE THREAD

**Issue by Aniverse** [orilights/hoyo-news-search#1]
有些讯息官网没有，而米游社虽然有搜索功能但也是一坨。
比如我想回顾一下崩铁 2.7 版本更新了哪些东西，完整的更新公告太长，看前瞻的一图流其实挺好的，这个原神会放官网，但是崩铁不放官网，得去米游社找

官方信息是指活动+公告+咨询：https://www.miyoushe.com/sr/home/53

**Comment by orilights** [comment]
大概看了下数据格式，没反爬的话应该可以加入，之后有空研究一下

**Comment by orilights** [comment]
已初步支持米游社信息获取
